FEATURE_KNOWLEDGE = {

    "MI_dir_L0.01_weight": {
        "technical":
            "Measures traffic magnitude within a short time window.",

        "security":
            "Sudden increases in traffic volume are common during botnet and DDoS attacks.",

        "interpretation":
            "The model observed abnormal traffic volume compared to normal device behavior."
    },

    "HH_jit_L0.01_variance": {
        "technical":
            "Measures variability in packet timing between communicating devices.",

        "security":
            "Irregular packet timing often appears during scanning, flooding, and botnet activity.",

        "interpretation":
            "The model detected unstable communication timing patterns."
    },

    "HpHp_L0.01_std": {
        "technical":
            "Measures stability of communication between network ports.",

        "security":
            "Attack traffic often creates abnormal port communication patterns.",

        "interpretation":
            "The model noticed unusual port-to-port communication behavior."
    },

    "H_L0.01_weight": {
        "technical":
            "Measures traffic intensity generated by a device.",

        "security":
            "Compromised devices often generate significantly more traffic than normal.",

        "interpretation":
            "The model identified abnormal traffic generation from the device."
    },

    "HpHp_L0.01_weight": {
        "technical":
            "Measures intensity of communication between ports.",

        "security":
            "Botnets frequently create unusual port activity patterns.",

        "interpretation":
            "The model detected suspicious communication intensity between ports."
    }
}